apiVersion: v1
kind: Namespace
metadata:
  name: swasthkart
  labels:
    app.kubernetes.io/part-of: swasthkart
---
apiVersion: v1
kind: Namespace
metadata:
  name: swasthkart-data
  labels:
    app.kubernetes.io/part-of: swasthkart
