apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swasthkart-ingress
  namespace: sk-dev
  labels:
    app.kubernetes.io/name: swasthkart-ingress
    app.kubernetes.io/instance: swasthkart-ingress-dev
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: swasthkart
    app.kubernetes.io/managed-by: kubectl
    swasthkart.io/team: platform
    swasthkart.io/tier: edge
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /health/live
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: bff-gateway
                port:
                  number: 3000
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: bff-gateway
                port:
                  number: 3000
